-- 1-- Exercise GroupBy LocationWiseMinAge
SELECT CUSTLOCATION AS "LOCATION", MIN(AGE) AS "MINIMUMAGE"
FROM CUSTOMER
GROUP BY CUSTLOCATION;

-- 2-- Exercise GroupBy Recent PurchaseDate
SELECT CUSTID, MAX(PURCHASEDATE) AS "RECENTPURCHASEDATE"
FROM INVOICE
GROUP BY CUSTID;

-- 3-- Exercise GroupBy White Products
SELECT BRAND, COUNT(*) AS "NOOFWHITEPRODUCTS"
FROM PRODUCT
WHERE COLOR = 'White'
GROUP BY BRAND;

-- 4: Exercise GroupBy Recent Purchase DateProductWise
SELECT CUSTID, PRODUCTID, MAX(PURCHASEDATE) AS "RECENTPURCHASEDATE"
FROM INVOICE
GROUP BY CUSTID, PRODUCTID;

-- 5: Exercise GroupBy LocationWiseMinAgeOfEachGender
SELECT CUSTLOCATION AS "LOCATION", GENDER, MIN(AGE) AS "MINIMUMAGE"
FROM CUSTOMER
GROUP BY CUSTLOCATION, GENDER
ORDER BY CUSTLOCATION, GENDER;
