-- HAVING FUNCTION
-- 1: Exercise_GroupBy_MinAgeAtleast30
SELECT CUSTLOCATION AS "LOCATION", MIN(AGE) AS "MINIMUMAGE"
FROM CUSTOMER
GROUP BY CUSTLOCATION
HAVING MIN(AGE) >= 30;

-- 2: Exercise GroupBy_LoyalCustomers
SELECT CUSTID, VENDORID, PRODUCTID,
       COUNT(QUANTITYPURCHASED) AS "NOOFPURCHASES"
FROM INVOICE
GROUP BY CUSTID, VENDORID, PRODUCTID
HAVING COUNT(QUANTITYPURCHASED) > 1;
