-- 1 : Exercise GroupBy Month
SELECT TO_CHAR(PURCHASEDATE, 'MON') AS "MONTH",
       COUNT(QUANTITYPURCHASED) AS "NUMBER_OF_PURCHASES"
FROM INVOICE
GROUP BY TO_CHAR(PURCHASEDATE, 'MON')
ORDER BY COUNT(QUANTITYPURCHASED) DESC;

-- 2 : Exercise GroupBy TotalQuantity
SELECT PRODUCTID,
       SUM(QUANTITYPURCHASED) AS "TOTAL_QUANTITY"
FROM INVOICE
WHERE QUANTITYPURCHASED > 1
GROUP BY PRODUCTID
HAVING SUM(QUANTITYPURCHASED) > 1;
